### ISSUE TITLE
Zcash weekly eco system digest 

### ISSUE THREAD

**Issue by dvdt3ddy** [ZecHub/zechub#1043]
ECC update :[ https://x.com/zcashtr/status/1842533250486476841?s=46](https://x.com/zcashtr/status/1842533250486476841?s=46)
[ https://electriccoin.co/blog/coinbase-zashi-1-2-release/](https://electriccoin.co/blog/coinbase-zashi-1-2-release/)
[ https://forum.zcashcommunity.com/t/ecc-update/48919](https://forum.zcashcommunity.com/t/ecc-update/48919)
https://forum.zcashcommunity.com/t/focused-ecc-update/48735
https://forum.zcashcommunity.com/t/a-culture-of-discipline-ecc-update/48963

https://forum.zcashcommunity.com/t/the-ecc-kitchen/48761/14

ZF updates:[ https://forum.zcashcommunity.com/t/zf-engineering-update-2024-sprint-19-september-10th-september-23rd/48916](https://forum.zcashcommunity.com/t/zf-engineering-update-2024-sprint-19-september-10th-september-23rd/48916)

https://forum.zcashcommunity.com/t/fundraising-campaign-to-represent-zcash-in-europe/48539/33

Zcash community grants :[ https://forum.zcashcommunity.com/t/zcash-community-grants-meeting-minutes-9-30-2024/48958](https://forum.zcashcommunity.com/t/zcash-community-grants-meeting-minutes-9-30-2024/48958)
-https://forum.zcashcommunity.com/t/grant-update-zcash-ecosystem-security-lead/47541/12
[-https://forum.zcashcommunity.com/t/zcash-developer-relations-engineer/48368/8 ](https://forum.zcashcommunity.com/t/zcash-developer-relations-engineer/48368/8)
https://forum.zcashcommunity.com/t/arti-year-ii-funding-plan-onion-services-and-more/41387/39

https://forum.zcashcommunity.com/t/zcash-developer-relations-engineer/48368/9

zcash community projects: https://x.com/zooko/status/1841584823187734850?s=46

https://x.com/zcashmedia/status/1841472378586481118?s=46

https://forum.zcashcommunity.com/t/zcash-shielded-asset-swaps-and-transaction-acceptance/48432/24

https://x.com/beyond_karto/status/1840780464501485643?s=46

https://x.com/keystonewallet/status/1840776117734809930?s=46

https://x.com/zcashfoundation/status/1829191412283518983?s=46

Community tweets

https://x.com/zcashmedia/status/1842559751713898906?s=46

https://x.com/btcturtle/status/1841977684483834138?s=46

https://x.com/redeadzk/status/1841531382931325354?s=46

https://x.com/zcashmedia/status/1842527953386688690?s=46

https://x.com/redeadzk/status/1842190589523317115?s=46

https://x.com/zcastesp/status/1842125279516401764?s=46

Zcash meme :[ https://x.com/redeadzk/status/1842387292431782308?s=46](https://x.com/redeadzk/status/1842387292431782308?s=46)

https://x.com/moneromavrick/status/1842265967813910693?s=46

**Comment by zksquirrel** [comment]
thanks @dvdt3ddy
