### ISSUE TITLE
Video - Zcash Wallets Explainer

### ISSUE THREAD

**Issue by januszgrze** [ZecHub/zechub#27]

**Comment by januszgrze** [comment]
So, coming back to this. I think it would be good to create a video that explains the difference between z-addrs and t-addrs and why different wallets are good for different usecases. Basically, explain why users should opt for shielded wallets when self-custodying... idk.

**Comment by januszgrze** [comment]
happy to jump on a call with whoever wants to claim this

**Comment by nfl0** [comment]
I came across this issue while using ZecHub and I wanted to express my support for the feature request to allow filtering boards by multiple labels. As someone who frequently works on tasks that have multiple labels, I can see how this feature would be very helpful in organizing my workflow.

Thank you to the ZecHub team for considering this suggestion. Look forward to seeing this feature implemented in a future release.
