### ISSUE TITLE
zcash faqs

### ISSUE THREAD

**Issue by januszgrze** [ZecHub/zechub#38]
needs to be updated.

**Comment by januszgrze** [comment]
please create a document that contains questions and answers to the top 20 questions that people ask when they are learning about zcash. it might also be helpful to divide the document in sections like beginner, intermediate, etc

**Comment by Michae2xl** [comment]
I think we already have this, but we can refine - https://z.cash/support/faq/

Obs.: I translated most of them into Portuguese and published on Discord - Zcash Latam -> Informações -> FAQ.

![faq](https://user-images.githubusercontent.com/44928059/185214113-8fd19d3c-11fa-4b26-bb88-6e32bf276b36.jpg)
