### ISSUE TITLE
Discord and bounty distribution

### ISSUE THREAD

**Issue by HashingMachine** [ZecHub/zechub#434]
Discord is known for its data collection practices, which can lead to privacy issues. By using Discord for exchanging the details for bounty distribution, this privacy risk is extended to contributors, possibly discouraging users to contribute.

As a cryptocurrency related project, the privacy of the contributors should be one of its main concerns. Therefore, there should be a way to contact the repository owners without sacrificing one's privacy, such as email with PGP.

**Comment by HashingMachine** [comment]
Any progress on this matter?

**Comment by TonyAkinsWritesCrypto** [comment]
I am also interested in this issue. Keep me abreast of things!

**Comment by HashingMachine** [comment]
Any updates?
In any case, I believe I should be rewarded for my contributions. Can you guys please email me at the address in my commit messages? Thanks.

**Comment by JJ-Rogers** [comment]
> Any updates? In any case, I believe I should be rewarded for my contributions. Can you guys please email me at the address in my commit messages? Thanks.

Hey, we had brought this point up with the community earlier. 
I will rehash my thoughts in our next meeting Tuesday 23:00 UTC
Gist is that despite discord data collection - the benefits to contributors (accessibility & communication) outweigh drawbacks
Would be interested to get some research into the risks you describe, perhaps reference instances in which discord has sold user data & implications for crypto users - this we would absolutely reward. 
Thanks,

**Comment by TonyAkinsWritesCrypto** [comment]
My own thoughts, I don't think it's better done than we have it on Discord. Benefits outweighs drawbacks as you mentioned, it's still a balanced system I believe. 

It's part of what we give out as contributors, if it's still within one's community, it's safer and even official.
