### ISSUE TITLE
Create WIki page - Non-Custodial Exchanges

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#445]
Make a simple wiki document listing all non custodial exchanges that users can acquire Zcash 

Bounty: 1 ZEC

- Make distinction if exchange supports Transparent/Shielded Zcash
- Provide links to each website
- Please denote DEX vs Centralised services 
- May include logo's / screenshots

If possible, format document similarly to our [Wallet Page](https://wiki.zechub.xyz/intro-to-zcash-wallets)

**Comment by TonyAkinsWritesCrypto** [comment]
[Zcash Wiki Docs.docx](https://github.com/ZecHub/zechub/files/12415803/Zcash.Wiki.Docs.docx)

Hello, I have invested 2 days of research on this, and this is what I get.
