### ISSUE TITLE
Create Video Guide - non-custodial Zcash Exchanges

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#464]
Create Video Guide (Desktop) - non-custodial Exchanges

Bounty: 1.5 ZEC

- Begin with introducing Zcash + features of network on z.cash 
- Demo 1-3 different platforms 
- Please do not include intro/outro on video submission

Video length ~5-10mins

**Comment by KSSaiTeja** [comment]
/attempt #436 

i will create a video on this..? @JJ-Rogers how can i submit this video.. directky here..?

**Comment by JJ-Rogers** [comment]
> /attempt #436
> 
> i will create a video on this..? @JJ-Rogers how can i submit this video.. directly here..?

Hi @KSSaiTeja 

This task has already been claimed on https://dework.zechub.org
Join us in https://discord.gg/zcash - we have a design space where you can share your talents and we can assign a task for you!
