### ISSUE TITLE
Create Wiki Page - PGP Encryption 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#475]
Make a simple wiki document to introduce and provide steps for using PGP Encryption for our Privacy Tools section

Bounty: 1 ZEC

- brief introduction section 
- Available tools
- How to generate keys & using for email/messages
- Best Practices

This is intended to be a new user guide. 
Please include screenshots / diagrams where possible

**Comment by TonyAkinsWritesCrypto** [comment]
Pretty Good Privacy (PGP) is a cryptographic software package that provides secure communication over insecure channels. PGP uses a combination of encryption and digital signatures to ensure that only the intended recipient can read a message and that the sender is who they say they are.

Available Tools

There are many different PGP tools available, but some of the most popular ones include:
[GPG](https://gpgtools.org/): GPG is a free and open-source PGP implementation that is available for Windows, macOS, and Linux.

[PGPMail](https://www.openpgp.org/software/): PGPMail is a commercial PGP email client that is available for Windows and macOS. 


[Mailvelope](https://www.comparitech.com/blog/information-security/pgp-encryption-gmail/): Mailvelope is a free and open-source PGP extension for Gmail and Thunderbird. 

How to Generate Keys

To use PGP, you need to generate a pair of keys: How to generate PGP keys: 
Open your PGP software.
Click on the "Generate Key" button.
Enter your name and email address.
Choose the key length. The longer the key length, the more secure your keys will be.
Click on the "Generate" button.
Your PGP key pair will be generated.

How to Use PGP for Email

Once you have generated a PGP key pair, you can use it to encrypt and decrypt emails. To encrypt an email, you need to know the public key of the recipient. You can then use your PGP tool to encrypt the email using the recipient's public key.
The encrypted email will be unreadable to anyone who does not have the recipient's private key. To decrypt the email, the recipient can use their private key to decrypt the email. 


Best Practices

Here are some best practices for using PGP:
Keep your private key safe. The private key is the most important part of your PGP key pair. If someone gets your private key, they can decrypt any messages that have been encrypted with your public key.



safe with a PGP private key inside
Share your public key with people you trust. You can share your public key by sending it to them directly, or by uploading it to a PGP keyserver. 

Use strong passwords for your PGP keyring. Your PGP keyring is a file that stores your PGP keys. It is important to use a strong password to protect this file.

Keep your PGP software up to date. PGP software is constantly being updated to fix bugs and improve security. It is important to keep your software up to date to ensure that you are using the latest security features.

 How to encrypt an email with PGP

Open your PGP software.
Open the email you want to encrypt.
Click on the "Encrypt" button.
Enter the public key of the recipient.
Click on the "Encrypt" button.
The email will be encrypted
.
How to decrypt an email with PGP

Open your PGP software.
Open the encrypted email.
Click on the "Decrypt" button.
Enter your private key.
Click on the "Decrypt" button.
The email will be decrypted.
