### ISSUE TITLE
Create Wiki page - Zgo App

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#477]
Create simple wiki document to provide information on Zgo payment processor for Zcash.

Bounty: 1 ZEC

- Provide clear Step by Step guide for Zgo integration on Wordpress Store. 
- List Website & available resources. 
- Section for 'Other' Payment processors that accept Zcash

This is intended to be a new user guide
Provide screenshots / diagrams where possible

**Comment by anima-regem** [comment]
I would like to work on this. Can you assign me this?

**Comment by JJ-Rogers** [comment]
> I would like to work on this. Can you assign me this?

Hey @anima-regem, are you familiar with Zgo and/or Zcash?

Feel free to join us in discord: https://discord.gg/zcash

**Comment by anima-regem** [comment]
Currently I'm not, but I'd love to learn more

**Comment by RANJITHROSAN17** [comment]
Zgo Payment Processor for Zcash
Introduction
Welcome to the Zgo Payment Processor for Zcash guide! This document will provide you with comprehensive information on integrating the Zgo payment processor into your WordPress store, allowing you to accept Zcash (ZEC) payments. Whether you are a new user or an experienced merchant, this guide will walk you through the process step by step. 🚀💰

Table of Contents
Getting Started
What is Zgo?
Why Use Zgo?
Integration Guide
Step 1: Sign Up for Zgo
Step 2: Install Zgo Plugin
Step 3: Configure Zgo
Step 4: Test Zgo Integration
Website & Resources
Official Zgo Website
Zgo Documentation
Zcash Official Website
Other Payment Processors for Zcash
Conclusion

Getting Started
What is Zgo? 🤔
Zgo is a secure and user-friendly payment processor designed to facilitate Zcash (ZEC) transactions. It enables businesses to accept ZEC payments seamlessly, offering customers a privacy-focused and efficient payment experience. 🔒💳

Why Use Zgo? 🌍
Privacy-Focused: Zgo utilizes the privacy features of Zcash to protect both the payer and payee's sensitive transaction data. 🙈

Easy Integration: Integrating Zgo into your WordPress store is straightforward, as detailed in the following guide. 🛠️

Global Reach: Zcash is accepted worldwide, making it an excellent choice for international businesses. 🌎

Integration Guide
Step 1: Sign Up for Zgo
Visit the official Zgo website ([Zgo Official Website](https://www.zgopayments.com/)).

Sign up for a Zgo account by following the registration process. 📝

Step 2: Install Zgo Plugin
Log in to your WordPress admin dashboard.

Navigate to "Plugins" in the left-hand menu.

Click "Add New."

In the search bar, type "Zgo Payment Processor" and press Enter.

Locate the Zgo Payment Processor plugin and click "Install Now."

After installation, click "Activate." ⚙️

Step 3: Configure Zgo
In your WordPress dashboard, go to "Settings" > "Zgo Payment Processor."

Enter your Zgo API credentials provided during the Zgo registration process.

Configure payment settings such as currency, transaction fees, and payment confirmation.

Save your settings. 💼

Step 4: Test Zgo Integration
To ensure your integration is working correctly, make a test purchase on your WordPress store using Zgo as the payment method.

Verify that the payment goes through smoothly, and you receive a confirmation.

Check your Zgo account dashboard for the transaction details. ✔️💳

Website and Resources
Official Zgo Website 🌐
[Zgo Official Website](https://www.zgopayments.com/)
Zgo Documentation 📖
[Zgo Documentation](https://www.zgopayments.com/docs)
Zcash Official Website 🕊️
[Zcash Official Website](https://z.cash/)
Other Payment Processors for Zcash
If you're considering alternative payment processors that accept Zcash, here are a few options:

CoinGate: CoinGate allows businesses to accept various cryptocurrencies, including Zcash, through their payment gateway.

NOWPayments: NOWPayments offers a cryptocurrency payment gateway that supports Zcash and numerous other cryptocurrencies.

BitPay: BitPay is a popular cryptocurrency payment processor that occasionally supports Zcash, depending on their current offerings.

Make sure to research these options further to determine which one best suits your business needs. 💼🌟

Conclusion
Congratulations! You have successfully integrated the Zgo payment processor for Zcash into your WordPress store. Zgo offers a secure and private way to accept ZEC payments, providing your customers with a convenient payment experience. If you have any further questions or need assistance, refer to the resources mentioned in this guide or contact Zgo's support team for help. Happy selling! 🎉🛒

**Comment by JJ-Rogers** [comment]
@RANJITHROSAN17 great stuff! Would you mind joining us in https://discord.gg/zcash

**Comment by TonyAkinsWritesCrypto** [comment]
Good job 👍
