### ISSUE TITLE
Create Wiki page - Places to spend ZEC

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#478]
Create a simple wiki document that lists: 'Top 10 Places to Spend Zcash'

Bounty: 1 ZEC

- Start with brief paragraph on WHY a company/service may wish to accept Zcash
- May include sites/services/donations/social networks 
- Please specify whether shielded/transparent ZEC accepted
- Include images of each site/service

**Comment by anima-regem** [comment]
Can I have this assigneed to me, I'd like to work on it.

**Comment by TonyAkinsWritesCrypto** [comment]
[MediaWiki.docx](https://github.com/ZecHub/zechub/files/12475531/MediaWiki.docx)

**Comment by TonyAkinsWritesCrypto** [comment]
[Markdown. MD ](https://github.com/ZecHub/zechub/files/12476297/Markdown.MD)

**Comment by TonyAkinsWritesCrypto** [comment]
Top 10 Places to Spend Zcash

[Zcash](https://z.cash/) is a privacy-focused cryptocurrency that offers users the option to make both transparent and shielded transactions. This makes it a popular choice for businesses and services that want to protect the privacy of their customers.

Here are the top 10 places to spend [Zcash](https://z.cash/):
[Dunkin' Donuts](http://news.dunkindonuts.com/) accepts Transparent [Zcash](https://z.cash/) through the SPEDN app at over 12,000 locations in the United States.
           


[Chipotle](https://www.chipotle.com/) started accepting [Zcash](https://z.cash/) payments last summer, also through Flexa's SPEDN app. Chipotle get transparent ZEC also. 
            
[FYM Hot sauce](http://fymhotsauce.rocks/) is a hot sauce company that accepts [Zcash](https://z.cash/) payments directly on their website. The company accept Shielded ZEC for transactions. 
            
  
[La Pasta](https://www.pinterest.com/pin/385902261813870666/) is a restaurant in San Francisco that allows for Transparent [Zcash](https://z.cash/) payments in-store. 

        


[B&N Cafe](http://www.alamoanacenter.com/) is a coffee shop chain that accepts [Zcash](https://z.cash/) payments The coffee chain also accepts Transparent ZEC 
          


[Red Rock Cafe](http://backdoorbbq.com/) is a restaurant in Las Vegas that accepts [Zcash](https://z.cash/) payments in-store. 


[Able Ebeneezer](http://www.taphunter.com/) is a clothing store in New York City that accepts [Zcash](https://z.cash/) payments in-store. 
            
[SheEmprende](http://www.sheemprende.com/) is a non-profit organization that supports female entrepreneurs and accepts  [Zcash](https://z.cash/) donations. It accepts Shielded ZEC.



[Wikileaks](http://commons.wikimedia.org/) accepts [Zcash](https://z.cash/) donations through their website. WikiLeaks is a publisher and media organisation founded in 2006. It operates as a non-profit and is funded by donations and media partnerships. Also allows Transparent ZEC transactions. 
           


 [MoneroTalk](http://www.instagram.com/) is a podcast about Monero and cryptocurrencies that accepts Transparent [Zcash](https://z.cash/) donations through the website.
  
There are several reasons why a company or service may wish to accept Zcash.

Privacy: Zcash offers users the option to make private transactions, which can be appealing to businesses and services that want to protect the privacy of their customers.

Security: Zcash is a secure cryptocurrency that uses strong cryptography to protect user funds.

Acceptance: The number of merchants that accept Zcash is growing, which makes it a more attractive option for businesses and services.

Marketing: Accepting Zcash can be a good way to attract new customers and promote the business or service.

Shielded vs. Transparent ZEC

Zcash supports both shielded and transparent transactions. Shielded transactions are private, while transparent transactions are visible to the public.

The majority of the places listed above only accept transparent ZEC. However, there are a few that accept shielded ZEC, such as FYM Hot Sauce and SheEmprende.
