### ISSUE TITLE
Create Short Video - Paying for item with Zcash!

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#517]
Create Short Video - Paying for item with Zcash 

Bounty: 1 ZEC

- Show Zcash being used for any real world purchase! 
- Please mention which wallet is being used for payment
- Mention transaction fee / Any memo included

**Comment by dnyaneshwar-rede** [comment]
can we create video for buying top up Mobile recharge on Binance   @JJ-Rogers
