### ISSUE TITLE
Create Wiki Page - Secure Messengers 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#519]
Create Wiki Page - Secure Messengers 

Bounty: 1 ZEC 

Must include:
- Introduction 
- end-to-end encryption explained
- reasons why e2ee is necessary
- Please mention Signal / Bison Relay / Session app

This is intended as a new user guide in our Privacy Tools section.

**Comment by TonyAkinsWritesCrypto** [comment]
I'm interested in this task and I've also created Wiki Pages for Zec before. 

I guess Dework network is bad but I will put in enough effort to make an excellent wiki page again.
