### ISSUE TITLE
Create Poster - Zcash Shielded Assets 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#521]
Create Poster - Zcash Shielded Assets 

Bounty: 1 ZEC

Creatively List/Display ZSA use cases:

- Governance Tokens 
- Non-Fungible Tokens 
- Stablecoins 
- Bridged assets

- Background HEX color: #154734;
- [Font type](https://www.urbanfonts.com/fonts/Arcade_Interlaced.font)

**Comment by Hardaeborla** [comment]
I can do this

**Comment by amochuko** [comment]
@JJ-Rogers  Kindly find the design -> https://github.com/amochuko/zcash-poster-design/blob/main/zcash-shielded-assets-use-case.png
