### ISSUE TITLE
Create Short Video Animation - ZSA 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#532]
Create short video - animated 'ZSA' text 

Bounty: 1 ZEC 

Intended to serve as cutscene / intro clip for ZSA videos 
- Video Length ~4 seconds 
- Please use color theme of [ZSA logo](https://wiki.zechub.xyz/zcash-technology/zcash-shielded-assets)

**Comment by HammadRafique29** [comment]
@JJ-Rogers  Issue still open?
