### ISSUE TITLE
Create a  RPi4 guide for zebrad

### ISSUE THREAD

**Issue by dismad** [ZecHub/zechub#538]
Similar to [this](https://github.com/ZecHub/zechub/blob/main/site/guides/RaspberryPi4FullNode.md), we are looking for an update-to-date guide using the latest zebrad on a Raspberry PI4 (or equivalent).

Bounty: 1-1.5 ZEC

**Comment by TonyAkinsWritesCrypto** [comment]
I've expressed my interest on Dework for this task. Having enough experience about Zcash ecosystem and I've been a contributor in the community. I have written a couple of wiki pages, newsletters sff importantly, I've written technical guides for the ZecHub. 


Check my messages on Dework m thanks
