### ISSUE TITLE
ZecWeekly #63 Community Newsletter Oct 7th

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#542]
[ZecWeekly Editions](https://zechub.substack.com/) are posted once a week.

Submit a complete newsletter with links to Zcash & Privacy ecosystem News/Events/Community Tweets/Memes

Bounty: 0.5 ZEC

We also accept translated newsletters! Join us on https://discord.gg/zcash to find out more

[Example](https://github.com/ZecHub/zechub/blob/main/newsletter/zecweekly50.md) / [Template](https://github.com/ZecHub/zechub/blob/main/newsletter/newslettertemplate.md)

**Comment by TonyAkinsWritesCrypto** [comment]
# ZecWeekly Update (Episode 63)

Zcash Diverse proposals, Minor Grants and Applications, Zcash Arborist Updates, Zcash 5.7.0 Upgrade Alert, Power of free2z. 

---

Curated by "TonyAkins" [@TonyAkins](https://twitter.com/TonyAkins01)


---

#### Welcome to ZecWeekly

This week's edition underscores major milestones in the Zcash Ecosystem; a productive era. New Zcash wallet features, Zcashd Utilities , Zcash mobile top up. 
---
Educational Content of the week. 

This week's edition will educate us on how to create a store that accepts Zcash as a result of massive growth in the system. 

The link to the resource is below

https://free2z.cash/ZecHub/zpage/zcash-101-create-store 

## Zcash Updates

ECC and Zcash Update

[Upgraded Privacy Tools] (https://twitter.com/ZecHub/status/1709272428457689205)

[ECC Welcomes Trina Larson: Healthcare Innovator](https://twitter.com/ECCIntegrator/status/1706752001080426646)

[Boosting Zcash Security w/ Zebra]
(https://www.youtube.com/watch?v=02N5uP5-7u)

[Upgrade Alert: Zcashd 5.7.0 Release!]
(https://twitter.com/ElectricCoinCo/status/1710049573954068505) 

[Brave, Electric Coin Co., and Filecoin Foundation announce partnership to bring new privacy tools to Web3](https://twitter.com/ZcashForum/status/1710407974437662887)


#### Zcash Community Grants Updates

[Zcash Minor Grants Diverse Proposals]

(https://twitter.com/wobbz2z/status/1709040476798730304) 

[RFP - Zcash Ecosystem Security Lead (2023)](https://forum.zcashcommunity.com/t/rfp-zcash-ecosystem-security-lead-2023/45723?utm_source=dlvr.it&utm_medium=twitter)

[Zcash Chart Hopium Tech Revealed!]
(https://twitter.com/ZcashForum/status/1710408044750970918) 


#### Community Projects


[Naira  Mobile Top-Up using Zcash,How-to guide]
(https://www.youtube.com/watch?v=BthMWMWnmc0)

[New Zcash Wallet feature! Spend before Sync]
(https://www.youtube.com/watch?v=ng2K28edQy4)

[ZecHub Community Achieves 100 Dework Tasks](https://twitter.com/ZecHub/status/1708814142222577705)

#### News & Media

[Sam Bankman-Fried goes on trial: A week in review](https://cointelegraph.com/news/sam-bankman-fried-ftx-goes-on-trial-week-review)

[Bitcoin Miner Iris Energy Jumps 9% as It Boosts Mining Capacity Ahead of Bitcoin Halving](https://decrypt.co/200491/bitcoin-miner-iris-energy-jumps-9-as-it-boosts-mining-capacity-ahead-of-bitcoin-halving)

[Bitcoin Grapples with $28K Resistance, but ‘Uncorrelated Asset’ Allure Could Mean Higher Prices, Says Analyst]

(https://www.coindesk.com/markets/2023/10/06/bitcoin-grapples-with-28k-resistance-but-uncorrelated-asset-allure-could-mean-higher-prices-says-analyst/?utm_medium=referral&utm_source=rss&utm_campaign=headlines)

[72% of CEOs Consider Generative AI a Top Investment Priority: KPMG](https://decrypt.co/200400)


[Binance spot market share drops for 7th consecutive month: Report](https://cointelegraph.com/news/crypto-binance-spot-market-share-drops-7th-month)

[ 3 reasons why Bitcoin is struggling to rally above $28.5K](https://cointelegraph.com/news/3-reasons-why-bitcoin-struggles-to-rally-above-29k)

[Elon Musk hits at SEC, DOJ amid suit to force testimony in Twitter probe](https://cointelegraph.com/news/elon-musk-scorns-sec-doj-lawsuit-twitter-purchase)

[UK must loosen KYC demands for crypto to outpace US in Web3 —Think tank](https://cointelegraph.com/news/uk-must-loosen-kyc-demands-for-crypto-to-outpace-us-in-web3-think-tank)

[Crypto for Advisors: Waiting for the Next Crypto Bull Market? It’s Already Here](https://www.coindesk.com/markets/2023/10/05/crypto-for-advisors-waiting-for-the-next-crypto-bull-market-its-already-here/?utm_medium=referral&utm_source=rss&utm_campaign=headlines)

[Bitcoin miners Marathon, Riot, CleanSpark increase BTC output in September](https://cointelegraph.com/news/bitcoin-miner-marathon-digital-riot-platforms-increase-btc-production)


## Some Zcash Tweets


[20 New Zcash Grant Applications](https://twitter.com/ZcashFoundation/status/1709250537470718201)

[Zcash in Schools: Exploring Possibilities!](https://twitter.com/OGA4SKY/status/1710325272644342049)

[Zcash Payments? Explore ZGoCash Guides!](https://twitter.com/ZecHub/status/1709981341234683966)


[Zcash Minor Grants approval poll (October 2023) went to SPAM](https://twitter.com/ZcashForum/status/1710407393161707641)

[Bitlendr - Lock Zcash, Unlock Cash](https://twitter.com/ZcashForum/status/1710407402171105408)

[Unstoppable Wallet integrating the latest Zcash update](https://twitter.com/ZcashForum/status/1710407384647246139)

[RFP - Zcash Ecosystem Security Lead (2023](https://twitter.com/ZcashForum/status/1710407375260373101)

[Top Messenger Apps by ZecHub](https://twitter.com/ZecHub/status/1709272428457689205) 

[Voice your support for proposals on Zcash Forum](https://twitter.com/ZcashFoundation/status/1709250567409713288)

[Burn the Old to Create the New System with XRP &ZCASH](https://twitter.com/ZcashForum/status/1710408024291262785)


## Zeme of the Week

[https://twitter.com/mad_paiement/status/1710347860397679079](https://twitter.com/mad_paiement/status/1710347860397679079)




## Jobs in the Ecosystem

- [Create Video Guide - Setup Zcash Full Node on AkashNetwork](https://github.com/ZecHub/zechub/issues/231)
