### ISSUE TITLE
Create Poster - Zebra Node Compile 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#561]
Create Poster - Steps-by-Step Compile Zebra Node 

Bounty: 1.2 ZEC 

- Please detail hardware requirements 
- Numbered Steps
- "Independent Node Implementation of Zcash Protocol"
- Run Local Block Explorer & Visualised Network Metrics 

[Information Source](https://github.com/ZcashFoundation/zebra#getting-started)
Let me know if you need help!

**Comment by Ritikkhulbe** [comment]
Hey can i contribute to this issue? im fairly new to git/github.

**Comment by JJ-Rogers** [comment]
> Hey can i contribute to this issue? im fairly new to git/github.

Hey, sorry this task has been done already 

You can join the Zcash Discord to find more tasks and events happening -> https://discord.gg/zcash 

To apply for tasks please use the Dework -> https://dework.zechub.org
