### ISSUE TITLE
Create Video HOWTO - Setup WSL in windows, and compile lastest zcashd

### ISSUE THREAD

**Issue by dismad** [ZecHub/zechub#567]
## Summary
Most folks use Windows as their OS of choice, but zcashd is only available in Linux. 

## Request

We are looking for a video that highlights:

- How to setup WSL in windows
- Download the latest zcashd source
- Compile zcashd within Windows using WSL
- Sync node the latest block height and [send your first node tx](https://www.youtube.com/watch?v=KNhd1KC0Bqk)

## Requirements

-  15 minutes or less, try and keep video as short and concise as possible
-  Needs to include a tx ID that we can verify was sent from a node running in windows
-  Have fun!

note: a synced node takes up over 265 GB of space, please make sure you have this space available :)
![Screenshot_2023-10-18_09-07-59](https://github.com/ZecHub/zechub/assets/81990132/abfd1e51-21ce-4e2d-be95-6c0d65ad91f2)

note2: keep funds amount small until you are comfortable , this is an educational exercise. 
## Bounty

3 ZEC

**Comment by TouchstoneTheGreat** [comment]
@dismad @TonyAkinsWritesCrypto is this bounty up/available ?
