### ISSUE TITLE
Create Vertical Inforgraphic Poster - Namada 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#592]
Create a vertical poster with information about Namada Blockchain 

Bounty: 1.2 ZEC 

- Uses Zcash Sapling Circuit
- Cosmos IBC ecosystem
- Shielded Transactions 
- Transparent + Private assets 
- Multi Asset Shielded Pool (MASP)
- Shielded Set rewards 

[Useful Resource](https://wiki.zechub.xyz/namada-protocol)

[Design/Style guide](https://namada.net/visual-identity)

Let me know if you need help!

**Comment by amochuko** [comment]
Done. Kindly find here.

https://github.com/amochuko/zcash-poster-design/blob/main/Inforgraphic%20Poster%20-%20Namada.png
