### ISSUE TITLE
Create AI image for - "Privacy is Normal"

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#596]
Create square image for - "Privacy is Normal" 

Bounty: 0.7 ZEC

- To be used as card on new wiki site 
- AI generated image is ok 
- If possible incorporate 3d design 

[Basis for Design](https://twitter.com/ZecHub/status/1694417573541007445)

**Comment by Tashuuuu** [comment]
I would like to work on it

**Comment by Tashuuuu** [comment]
There is a "newsletter/ZecWeekly66.md" file that has not been committed yet. I hope you solve it as soon as possible so that I can continue working on the issue.

**Comment by JJ-Rogers** [comment]
> There is a "newsletter/ZecWeekly66.md" file that has not been committed yet. I hope you solve it as soon as possible so that I can continue working on the issue.

Hi @Tashuuuu please note we assign tasks to contributors on https://dework.zechub.org 

you can join the Zcash global discord to gain access. https://discord.gg/zcash
