### ISSUE TITLE
Update ZecHub DAO page 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#607]
Update ZecHub DAO page 

Bounty: 1 ZEC 

- Add new Members to list 
- Include new site links 
- Add section on previous proposals 
- Add new banner image 

Document must be submitted in Markdown here: https://github.com/ZecHub/zechub/blob/main/site/contribute/ZecHub_DAO.md

**Comment by abhi-0104** [comment]
Dework not working ssign here

**Comment by abhi-0104** [comment]
will be starting the work now

**Comment by stark0104** [comment]
@JJ-Rogers please assign the task to me. Tried to apply from dework but its not working

**Comment by FL3X46** [comment]
can ı work on this ?
