### ISSUE TITLE
Create Site images for Wallets page 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#608]
Create a site banner for our wallets page

Bounty: 1 ZEC 

- Create a banner and images for our new wallets page 
- Please upload to image hosting website and add links 
-   ![image description](link)   <-- this is how 

Must be added to this page in markdown format: https://github.com/ZecHub/zechub/blob/main/site/Using_Zcash/Wallets.md

**Comment by Girish4489** [comment]
is the issue still open, if yes @JJ-Rogers Could you please assign this task to me?
