### ISSUE TITLE
Create Poster - Ways to Accept ZEC payments 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#616]
Create Poster - "Ways to Accept Zcash payments"

Bounty: 1 ZEC 

- Direct to Wallet (Zingo / Nighthawk / Ywallet logos etc)
- Include link to: https://z.cash/wallets 
- Shielded Payments protect customer information 
- Show Zgo Payment Processor logo + site link

**Comment by GarvAgarwal26** [comment]
Hey, Can u please assign this task to me ....I will make sure to handle it sincerely :)
