### ISSUE TITLE
Create Poster for AtomicDEX 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#620]
Create Poster for AtomicDEX 

Bounty: 1 ZEC 

- KMD to ZEC swaps 
- Low Fees! 
- Non-Kyc 
- Non-Custodial 
- Browser & Mobile Compatible 

More information: https://atomicdex.io/en/
Please include logos and color scheme for KMD + Zcash

**Comment by nityam2002** [comment]
Can you add a bit more details? 

- What are the dimensions?
- What do you want it for? 
- Do you need it in an informative manner and text-heavy or in a banner for social media?
- If there are other company guidelines regarding texts and images, please add them too.

**Comment by GarvAgarwal26** [comment]
Hey @nityam2002 , As it is my first bounty Can I work with you...I really want to collaborate on this.. it would be great if I can help u in any way, this will really help boost my confidence

Hope you understand, Thanks :)

**Comment by nityam2002** [comment]
@SharkyBytes 

Of course. Once we have any new information or updates, we can get started.
