### ISSUE TITLE
Create Video HOWTO - Using Docker to install Zebra full node

### ISSUE THREAD

**Issue by dismad** [ZecHub/zechub#621]
## Summary

[Docker](https://www.docker.com/) is powerful but can be confusing to learn. Briefly show the basics of how to use Docker and use it to install the latest Zebra full node.

## Request

We are looking for a video that highlights:
- How to install Docker
- Show the basic usage of popular Docker commands
- Install and sync the latest Zebra full node using Docker
- How to start and stop the node as needed

## Requirements

- 15 minutes or less, try and keep video as short and concise as possible
-  Talk about what was most confusing to you during this learning process
-  Have fun!

# Bounty

3 ZEC

**Comment by vignan37** [comment]
I want to claim this bounty. Assign it to me
