### ISSUE TITLE
Create Video Demo - Atomic DEX WebApp

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#633]
Create Video Demo - Atomic DEX WebApp

Bounty: 1.5 ZEC

- Explain benefits of using DEX vs CEX
- Show various pairs available on platform 
- Demo Zcash Swap 
- Video length ~5mins

Privacy advantage using web app vs locally stored application: https://forum.zcashcommunity.com/t/decentralized-exchanges-dexs/45993/17

Resource: https://app.komodoplatform.com/#/dex

**Comment by dnyaneshwar-rede** [comment]
Can we create video in Hindi language @JJ-Rogers
