### ISSUE TITLE
Add Toastify Notification bar to ZecHub Landing page

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#646]
Add Toastify Notification bar to ZecHub Wiki landing page

Bounty: 6 ZEC

- Push Notifications of New Posts on https;//forum.zcashcommunity.com
- Push Notifications of New Posts from @Zcash Twitter Account

Wiki site is a NextJS app

Please apply for task via dework: https://dework.zechub.org

**Comment by nicefacer** [comment]
Hello @JJ-Rogers , Let me complete this task, I have applied on dework.
