### ISSUE TITLE
Create Comparison Table - Zcash vs Other Privacy Coins

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#652]
Create Comparison Table - Zcash vs Other Privacy Coins

Bounty: 1.5 ZEC 

- Please include: Firo / Dash / Litecoin / Monero / Secret Network 
- Features: Shielded Pool / Verifiable Proof System / Smart Contracts / User Defined Assets / Payment Disclosures / Staking 

[Example](https://www.exceltemplates.com/wp-content/uploads/2018/06/comparison-chart-template-1.jpg)

Please apply for task via dework: https://dework.zechub.org

If you need help completing this task, please ask.

**Comment by HarjobandeepSingh** [comment]
@JJ-Rogers can you assign me for this task
