### ISSUE TITLE
Create  Animated Logo - Namada 

### ISSUE THREAD

**Issue by zksquirrel** [ZecHub/zechub#663]
Create Animated Logo - Namada/Atom/Shield

Bounty: 1.5 ZEC

Animation duration 4 seconds
500px 500px
Please incorporate themes: Atom / Shield 
Intended to be used as loading animation for website.
Example: https://codepen.io/Tushar9024/pen/qBLGXmo
Please see Namada Visual Identity: https://namada.net/visual-identity

Please apply for this task via dework: https://dework.zechub.org/

**Comment by FL3X46** [comment]
can ı work on this ?
