### ISSUE TITLE
Reformat Zechub.wiki site URL's 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#664]
Reformat Zechub.wiki URL's 

Bounty: 1.5 ZEC

Please correct the following: 
- remove uppercase characters 
- remove special characters (underscores) 
- remoce "site" prefix 

Website is a NextJS app
Site repository: https://github.com/zechub/zechub-wiki

Please apply for this task via dework: https://dework.zechub.org

**Comment by ColdMice** [comment]
hey @JJ-Rogers I have applied via dework, can you assign this to me
