### ISSUE TITLE
ZecHub Wiki - Add donation page 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#668]
ZecHub Wiki - Add donation page 

Bounty: 2 ZEC 

- Add a new page to zechub wiki 
- Must have button on landing page 
- Page is intended for donations 

Wiki Site is a Nextjs app
Site repository: https://github.com/ZecHub/zechub-wiki

Please apply for this task on dework: https://dework.zechub.org

**Comment by ravalkenil** [comment]
Can you assign me?
