### ISSUE TITLE
Create Wiki Page - Payment Request URI's 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#677]
Create Wiki Page - Payment Request URI's 

Bounty: 1.2 ZEC

Must include link to the Zcash Improvement Proposal: https://zips.z.cash/zip-0321
Brief description of dynamic QR codes 
List use cases for payment requests 
[Provide code example](https://github.com/ZecHub/zechub-wiki/tree/main/src/components/Donation) + [Mobile wallet guide](https://www.youtube.com/watch?v=l5auYQIzYsQ)

Submit page as markdown document as pull request to: https://github.com/ZecHub/zechub/tree/main/site/Using_Zcash

Please apply for this task on dework: https://dework.zechub.org/

**Comment by amochuko** [comment]
Hello there;

Having submitted a task that was related to this topic previously; and made some research on the subject matter; I would appreciate to use the same knowledge to work on this task.

Thanks for your consideration.

**Comment by TonyAkinsWritesCrypto** [comment]
Being a technical writer and already written a few Wiki Pages for Zcash on this platform, amongst other related topics. I'm interested to work with on this. 


It'll be an outstanding  technical content for Zcash and its ever growing ecosystem. I'll be glad to take this role. Thanks.
