### ISSUE TITLE
Remove 3 Banners from Zechub.wiki

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#678]
Replace Banners from Zechub.wiki

Bounty: 1.5 ZEC 

- Replace "what is zcash" / "privacy is normal" / "zcash shielded assets" sections 
- Replace with transparent "frame" 
- Will offer guidance on task 

Site repository: https://github.com/ZecHub/zechub-wiki
Website is NextJS app 

Please apply for this task on dework: https://dework.zechub.org/

**Comment by aliraza556** [comment]
Hi @JJ-Rogers,
Assign me
