### ISSUE TITLE
ZecHub.Wiki - Mobile Responsiveness

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#683]
Apply Mobile Responsiveness Improvements to ZecHub.Wiki

Bounty: 3 ZEC 

- Add Dynamic Features 
- Align drop down menus to left & increase size -> [example](https://ethereum.org)
- Logo/Homepage should be visible on mobile 
- Remove social links from top bar 

PR must include Unit Test

Site repository: https://github.com/ZecHub/zechub-wiki
Website is NextJS app (Typescript / Tailwind)

Please apply for this task on dework: https://dework.zechub.org/

**Comment by ManyRios** [comment]
I'm fixing this with in my PR

**Comment by amochuko** [comment]
Hello there.

Am interested in taking up the task. I have personally observed this issues the last time I worked on the repo; so I understand this issue and thus would be grateful for the chance to get it fix.
