### ISSUE TITLE
Create "DAO" page on ZecHub.Wiki

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#684]
Create "DAO" page on ZecHub.Wiki

Bounty: 1.2 ZEC 

Create page for DAO --> zechub.wiki/dao 
- Move DAO information from homepage into dao page 

PR must include Unit Test

Site repository: https://github.com/ZecHub/zechub-wiki
Website is NextJS app (Typescript / Tailwind)

Please apply for this task on dework: https://dework.zechub.org/

**Comment by Sambit03** [comment]
Interested
