### ISSUE TITLE
Create "Wallets" page for ZecHub Wiki

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#687]
Create "Wallets" page for ZecHub Wiki

Bounty: 1.5 ZEC 

- Page should have 4 tiles 
- Mobile Wallets / Desktop Wallets / Web Wallets / Hardware Wallets
- URL - zechub.wiki/wallets

Site repository: https://github.com/ZecHub/zechub-wiki
Website is NextJS app (Typescript / Tailwind)

Please apply for this task on dework: https://dework.zechub.org/

**Comment by Sambit03** [comment]
Interested

**Comment by AliLordLoss** [comment]
Hello there. I'm interested in task too😄

**Comment by amochuko** [comment]
Hello there;

I would like to deliver on this task.

Thank you.

**Comment by JJ-Rogers** [comment]
Thanks @AliLordLoss
