### ISSUE TITLE
Create animated Gif for 'ZecWeekly' Community Newsletter

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#688]
Create animated Gif for 'ZecWeekly' Community Newsletter

Bounty: 1 ZEC

- Feature Zcash logo 
- ZecHub Color theme (light blue & white)
- See examples: https://zechub.substack.com

Be Creative! 

Please apply for this task on dework: https://dework.zechub.org/

**Comment by astadaniel2** [comment]
I can't wait to be given this task

**Comment by doloresampaio** [comment]
[https://www.canva.com/design/DAF-aG2A9xg/uINeQVUJq025ywfLcyDNiw/edit?utm_content=DAF-aG2A9xg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton](url)

**Comment by doloresampaio** [comment]
https://www.canva.com/design/DAF-aG2A9xg/uINeQVUJq025ywfLcyDNiw/edit?utm_content=DAF-aG2A9xg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by JJ-Rogers** [comment]
thank you @doloresampaio !
