### ISSUE TITLE
My First Zcash - Design Cover Page 

### ISSUE THREAD

**Issue by zksquirrel** [ZecHub/zechub#689]
My First Zcash - Design Cover Page 

Bounty: 

- Design must be consistent with MFZ Visual Identity (color palette)
- Create design for workbook Spine, & Back Cover
- Sensible but creative design is ideal! 

More information in MFZ channel: https://discord.gg/zcash

**Comment by doloresampaio** [comment]
I would love to be able to perform this task. thanks

**Comment by reikozec** [comment]
I'd like to do that task.

**Comment by Hardaeborla** [comment]
Interested

**Comment by elisehamdon** [comment]
This task has been completed by Mine
