### ISSUE TITLE
Create a Zcash wordsearch poster

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#690]
Create Zcash wordsearch game 11x11 letters 

Bounty: 1.5 ZEC 

- Feature wallets/terminology/organisations etc. 
- Please include fun background/border design 
- Resource: https://zechub.wiki 

Be creative!

**Comment by okeaguugochukwu** [comment]
I can handle the task very well

**Comment by theKroy** [comment]
this is a very interesting task, can’t wait to put my expertise to use; I would like to take this up.

**Comment by Hardaeborla** [comment]
I can do the design

**Comment by doloresampaio** [comment]
I would love to be able to perform this task. Thanks 🙂

**Comment by ezeobi** [comment]
Am ui/ux designer . Am fit for the task

**Comment by reikozec** [comment]
I'd like to do that task.

**Comment by Hardaeborla** [comment]
@JJ-Rogers 
![Zcash Crossword worksheet _20240302_144620_0000](https://github.com/ZecHub/zechub/assets/38798812/a5f64444-03d3-47f3-9b54-666ab261267f)

The answers to the puzzle 👇
![Answers](https://github.com/ZecHub/zechub/assets/38798812/efaeba0d-e33c-4da8-9c29-baf72649a434)

**Comment by JJ-Rogers** [comment]
thanks @Hardaeborla
