### ISSUE TITLE
ZecWeekly Community Newsletter 84 - March 2nd 

### ISSUE THREAD

**Issue by JJ-Rogers** [ZecHub/zechub#691]
[ZecWeekly Editions](https://zechub.substack.com/) are posted once a week.

Bounty: 0.85 ZEC

[Example](https://github.com/ZecHub/zechub/blob/main/newsletter/zecweekly81.md) / [Template](https://github.com/ZecHub/zechub/blob/main/newsletter/zecweekly81.md)

Markdown format requested.

Submit a complete newsletter with links to Zcash & Privacy ecosystem News/Events/Community Tweets/Memes to: https://github.com/ZecHub/zechub/tree/main/newsletter

We also accept translated newsletters! Join us on https://discord.gg/zcash to find out more

**Comment by okeaguugochukwu** [comment]
I can't  also handle this task if given

**Comment by TonyAkinsWritesCrypto** [comment]
I'm interested in this task. I'll like to create another episode of ZecWeekly Newsletter.

**Comment by TonyAkinsWritesCrypto** [comment]
Thanks so much @JJ-Rogers
